### ISSUE TITLE
Incorrect mode argument value for mkdir function

### ISSUE THREAD

**Issue by ivanarh** [DimitriFourny/unxip#1]
https://github.com/DimitriFourny/unxip/blob/deb889949c03f11a35d7123611dff7994394814e/unxip.cpp#L73
You've got an error in the value of mode argument:
`mkdir(dirpath.c_str(), 770);`
It must be 0770, it's an octal value.

**Comment by DimitriFourny** [comment]
Thank you, fixed in 4e67b673b66d5dedf76cecda4151b6ba55374b12.
